modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"

# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange=${neoVersionRange} #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]] #optional
    modId="geckolib" #mandatory
    type="required" #mandatory
    versionRange="[4.4.4,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]] #optional
    modId="curios" #mandatory
    type="required" #mandatory
    versionRange="[1.20.4-7.3.4,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange=${minecraftVersionRange}
    ordering="NONE"
    side="BOTH"